### ISSUE TITLE
Unable to link to a directory using @link ... @endlink in 1.15.0 and later

### ISSUE THREAD

**Issue by st-masa** [doxygen/doxygen#12189]
**Describe the bug**
In Doxygen 1.15.0 and later, linking to a specific directory using `@link` ... `@endlink` results in the following warning:
```
examples/example1.cpp:10: error: unable to resolve link to 'examples' for \link command
```

The example below links to the `examples` directory.

```
/**
  @page example1page
  @brief This is example1 page that is displayed.

  @details
    Link to examples directory: @link examples examples @endlink
 */
```

It is output as a <a> tag, but there is no href content.

```html
<p>Link to examples directory: <a class="el" href="">examples </a> </p>
```

**Screenshots**

<img width="594" height="259" alt="Image" src="https://github.com/user-attachments/assets/28654095-10bb-4c6d-84be-2394498faab4" />

**To Reproduce**

Attaching a sample to reproduce: [linkendlinkSample.zip](https://github.com/user-attachments/files/28417589/linkendlinkSample.zip).

**Expected behavior**

`@link`... `@endlink` link works correctly.

**Version**

1.15.0 and later

**Comment by albert-github** [comment]
Problem looks like to be introduced by:
c00a2de22453dfe701809423275355e486f3699b is the first bad commit
```
commit c00a2de22453dfe701809423275355e486f3699b

Date:   Tue Jun 3 21:18:51 2025 +0200

    issue #11593 Missing links for LaTex, RTF, ... with IMPLICIT_DIR_DOCS
```

Especially the change in `dirdef.cpp`

**Comment by doxygen** [comment]
@st-masa Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by albert-github** [comment]
Looks like this fix gives a problem with test 120 in respect to rtf files:
```
error: problems opening rtf file 'dir_f73c1a61975101f17e836d89b6db2a5d.rtf' for reading
error: An error occurred during post-processing the RTF files!
```

**Comment by albert-github** [comment]
Looks that also PDF generation fails:
```
...
! LaTeX Error: File `dir_f73c1a61975101f17e836d89b6db2a5d.tex' not found.
...
l.241 \input{dir_f73c1a61975101f17e836d89b6db2a5d}
...
```

**Comment by doxygen** [comment]
@albert-github I was already afraid of this. I've reverted the changes. I think it is a usage error by depending on a bug that has been fixed. The directory is not documented so it cannot be linked to (same would hold for link to other undocumented entities).

@st-masa Solutions:
1. set `EXTRACT_ALL=YES` so everything is treated as documented.
2. Document the directory, e.g. add  
```code
/**
 * @dir examples
 * @brief This is the examples directory.
 */
```

**Comment by st-masa** [comment]
@doxygen  I have confirmed your solutions.
* Setting `EXTRACT_ALL=YES` enables all undocumented output, so it is not applicable to my use case.
* Tried to explicitly document each directory by using \dir command with the setting `EXTRACT_ALL=NO` . After all, I can link to the target directories.

Attaching a sample with the documentation added to 'example' dir, and also its subdir. 
[linkendlinkSample2.zip](https://github.com/user-attachments/files/31179151/linkendlinkSample2.zip)

Thank you for your advise!
