### PR TITLE
fixed some parser bugs

### PR DESCRIPTION
**Pull request by maddox11**
this patch fixed some parser bugs #6997 #7442 and some older ones.

### CODE REVIEW

**Comment by albert-github** [comment]
I tried to compile with javacc 7.0.5 under Windows (Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27034 for x86) and got:
```
....
[ 22%] Building CXX object vhdlparser/CMakeFiles/vhdlparser.dir/VhdlParser.cc.obj
VhdlParser.cc
d:\programs\doxygen\fork\doxygen\qtools\qstring.h(68): error C2059: syntax error: 'constant'
d:\programs\doxygen\fork\doxygen\qtools\qstring.h(68): error C2238: unexpected token(s) preceding ';'
d:\programs\doxygen\fork\doxygen\qtools\qstring.h(408): error C2059: syntax error: 'constant'
d:\programs\doxygen\fork\doxygen\qtools\qstring.h(408): error C2238: unexpected token(s) preceding ';'
d:\programs\doxygen\fork\doxygen\qtools\qstring.h(525): error C2589: 'constant': illegal token on right side of '::'
d:\programs\doxygen\fork\doxygen\qtools\qstring.h(525): error C2062: type 'unknown-type' unexpected
```

and under Cygwin (gcc (GCC) 7.4.0) I got:
```
[ 21%] Building CXX object vhdlparser/CMakeFiles/vhdlparser.dir/VhdlParser.cc.o
In file included from /cygdrive/d/Programs/Doxygen/fork/doxygen/vhdlparser/VhdlParser.h:3:0,
                 from /cygdrive/d/Programs/Doxygen/fork/doxygen/vhdlparser/VhdlParser.cc:2:
/cygdrive/d/Programs/Doxygen/fork/doxygen/vhdlparser/JavaCC.h:44:14: error: expected unqualified-id before numeric constant
 #define null 0
              ^
/cygdrive/d/Programs/Doxygen/fork/doxygen/qtools/qstring.h:68:27: note: in expansion of macro ‘null’
     QT_STATIC_CONST QChar null;            // 0000
                           ^~~~
/cygdrive/d/Programs/Doxygen/fork/doxygen/vhdlparser/JavaCC.h:44:14: error: expected unqualified-id before numeric constant
 #define null 0
              ^
/cygdrive/d/Programs/Doxygen/fork/doxygen/qtools/qstring.h:408:23: note: in expansion of macro ‘null’
     static const Null null;
                       ^~~~
/cygdrive/d/Programs/Doxygen/fork/doxygen/qtools/qstring.h: In member function ‘QChar QString::at(uint) const’:
/cygdrive/d/Programs/Doxygen/fork/doxygen/vhdlparser/JavaCC.h:44:14: error: expected unqualified-id before numeric constant
 #define null 0
              ^
/cygdrive/d/Programs/Doxygen/fork/doxygen/qtools/qstring.h:525:45: note: in expansion of macro ‘null’
  { return i<d->len ? d->unicode[i] : QChar::null; }
                                             ^~~~
/cygdrive/d/Programs/Doxygen/fork/doxygen/vhdlparser/JavaCC.h:44:14: error: expected ‘;’ before numeric constant
 #define null 0
              ^
/cygdrive/d/Programs/Doxygen/fork/doxygen/qtools/qstring.h:525:45: note: in expansion of macro ‘null’
  { return i<d->len ? d->unicode[i] : QChar::null; }
                                             ^~~~
```

**Comment by doxygen** [comment]
@maddox11 Is this pull request still valid now that https://github.com/doxygen/doxygen/commit/ece0461582b622bc4051f1acb8f47f674bd8b232 has been pulled in?

**Comment by albert-github** [comment]
Seen the changes in doxygen, the fact that there are further no errors reported regarding this problem and the fact that there has been no response: I think this pull request can be closed
