### ISSUE TITLE
Error: return value NULL of function has multiple documentation sections

### ISSUE THREAD

**Issue by silvioprog** [doxygen/doxygen#7769]
Hi.

Consider the [following documentation](https://github.com/risoflora/libsagui/blob/master/include/sagui.h#L1347):

```c
/**
 * Creates a new HTTP server handle.
 * \param[in] auth_cb Callback to grant/deny user access to the server
 * resources.
 * \param[in] req_cb Callback to handle requests and responses.
 * \param[in] err_cb Callback to handle server errors.
 * \param[in] cls User-defined closure.
 * \return New HTTP server handle.
 * \retval NULL If no memory space is available.
 * \retval NULL If the \pr{req_cb} or \pr{err_cb} is null and sets the `errno`
 * to `EINVAL`.
 * \retval NULL If a threading operation fails and sets its error to `errno`.
 */
SG_EXTERN struct sg_httpsrv *sg_httpsrv_new2(sg_httpauth_cb auth_cb,
                                             sg_httpreq_cb req_cb,
                                             sg_err_cb err_cb,
                                             void *cls) __SG_MALLOC;
```

It worked fine in Doxygen 1.8.15 as showed here:

[https://risoflora.github.io/libsagui-docs/group__sg__httpsrv.html](https://risoflora.github.io/libsagui-docs/group__sg__httpsrv.html#ga3d4c9e9f5978b491bcf2ad6880d1fd67)

however, in Doxygen 1.8.17, it raises the following error at build time:

```bash
/workspaces/libsagui/include/sagui.h:1378: error: return value 'NULL' of sg_httpsrv_new2 has multiple documentation sections (warning treated as error, aborting now)
Exiting...
```

Since my library returns `NULL` in three situations, I would like to keep its documentation as it is.

So, how to configure Doxygen to solve those new introduced (useless) errors?

TIA for any help!

**Comment by albert-github** [comment]
I think it is correct that doxygen gives a warning, a return value (even `NULL`) is used under diffecent circumstances.

Why not create a nice list out of it like:
```
/**
 * Creates a new HTTP server handle.
 * \param[in] auth_cb Callback to grant/deny user access to the server
 * resources.
 * \param[in] req_cb Callback to handle requests and responses.
 * \param[in] err_cb Callback to handle server errors.
 * \param[in] cls User-defined closure.
 * \return New HTTP server handle.
 * \retval NULL
 *              - If no memory space is available.
 *              - If the \\pr{req_cb} or \\pr{err_cb} is null and sets the `errno`
 * to `EINVAL`.
 *              - If a threading operation fails and sets its error to `errno`.
 */
SG_EXTERN struct sg_httpsrv *sg_httpsrv_new2(sg_httpauth_cb auth_cb,
                                             sg_httpreq_cb req_cb,
                                             sg_err_cb err_cb,
                                             void *cls) __SG_MALLOC;
```

resulting in:

![new_result](https://user-images.githubusercontent.com/5223533/81503978-065bc680-92e7-11ea-8cfc-d883ba0c0c25.jpg)

(I had to escape `\pr` as I don't have the ALIAS, but this is irrelevant).


I think the problem is usage.

**Comment by silvioprog** [comment]
@albert-github Thanks a lot for answering!

This is a good idea, using topics makes the documentation more clear for multiple documentation sections. I'm going to use it.

Thanks one more time! :+1:
