### ISSUE TITLE
Doxygen fails to build using clang 19.1.6

### ISSUE THREAD

**Issue by jbigot** [doxygen/doxygen#11340]
**Describe the bug**
When building (through spack on Linux) Doxygen 1.12.0 using clang 19.1.6, I get compilation errors in the embedded version of TinyDeflate:

```
#8 3439.1 cd /tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-build-2uxa7ry/src && /opt/spack/lib/spack/env/clang/clang++ -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -DYY_BUF_SIZE=262144 -DYY_READ_BUF_SIZE=262144 -I/opt/install/linux-ubuntu20.04-x86_64_v2/clang-19.1.6/libiconv-1.17-ddulce6ie4fb27oxrz3ey2weafibkbgt/include -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/TinyDeflate -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/filesystem -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/libmd5 -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/liblodepng -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/libmscgen -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/libversion -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/libxml -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/vhdlparser -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/src -I/tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-build-2uxa7ry/generated_src -isystem /opt/install/linux-ubuntu20.04-x86_64_v2/clang-19.1.6/spdlog-1.14.1-ptebvjf3lvefiqehcffk6uquakj45emk/include -isystem /opt/install/linux-ubuntu20.04-x86_64_v2/clang-19.1.6/fmt-11.0.2-ipglqaoo3cnhbk5oitmo5ttn5e26hmpa/include -DJAVACC_CHAR_TYPE="unsigned char" -O3 -DNDEBUG -std=gnu++17 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wno-unused-parameter -Wno-implicit-int-conversion -Wno-sign-conversion -Wno-format-nonliteral -Wno-shorten-64-to-32 -Wno-gnu-zero-variadic-macro-arguments -MD -MT src/CMakeFiles/doxymain.dir/dotrunner.cpp.o -MF CMakeFiles/doxymain.dir/dotrunner.cpp.o.d -o CMakeFiles/doxymain.dir/dotrunner.cpp.o -c /tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/src/dotrunner.cpp
#8 3439.1 In file included from /tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/src/dotrunner.cpp:29:
#8 3439.1 /tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/TinyDeflate/gunzip.hh:1144:35: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
#8 3439.1  1144 |                 (tracker.template ForwardInput(i), tracker.template ForwardOutput(o), tracker.template ForwardWindow(c), std::forward<B>(b)));
#8 3439.1       |                                   ^
#8 3439.1 /tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/TinyDeflate/gunzip.hh:1144:69: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
#8 3439.1  1144 |                 (tracker.template ForwardInput(i), tracker.template ForwardOutput(o), tracker.template ForwardWindow(c), std::forward<B>(b)));
#8 3439.1       |                                                                     ^
#8 3439.1 /tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/TinyDeflate/gunzip.hh:1144:104: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
#8 3439.1  1144 |                 (tracker.template ForwardInput(i), tracker.template ForwardOutput(o), tracker.template ForwardWindow(c), std::forward<B>(b)));
#8 3439.1       |                                                                                                        ^
#8 3439.1 /tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/TinyDeflate/gunzip.hh:1151:35: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
#8 3439.1  1151 |                 (tracker.template ForwardInput(i),std::forward<O>(o),std::forward<C>(c),std::forward<B>(b)));
#8 3439.1       |                                   ^
#8 3439.1 /tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/TinyDeflate/gunzip.hh:1158:55: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
#8 3439.1  1158 |                 (std::forward<I>(i), tracker.template ForwardOutput(o), tracker.template ForwardWindow(c), std::forward<B>(b)));
#8 3439.1       |                                                       ^
#8 3439.1 /tmp/root/spack-stage/spack-stage-doxygen-1.12.0-2uxa7ryel5jivqbbddq66n2o5ugtqfsg/spack-src/deps/TinyDeflate/gunzip.hh:1158:90: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
#8 3439.1  1158 |                 (std::forward<I>(i), tracker.template ForwardOutput(o), tracker.template ForwardWindow(c), std::forward<B>(b)));
#8 3439.1       |                                                                                          ^
#8 3439.1 [ 75%] Building CXX object src/CMakeFiles/doxymain.dir/doxygen.cpp.o
```

The result can be reproduced through by building Doxygen in the system of the docker image ghcr.io/pdidev/test_env/builder:latest-clang-3c-e63c687 based on the latest version of the Spack distribution (on top of Ubuntu Focal Fossa)

The build process is the one described in https://github.com/pdidev/test_env/blob/v3/spack/4a-baselibs/Dockerfile with:
* VERSION=latest
* COMPILER=clang
* IMAGE_TAG=e63c687 

An example of this can be consulted at https://github.com/pdidev/test_env/actions/runs/12738200478/job/35504284857

**Comment by jbigot** [comment]
Sorry, I just realized this is fixed in 1.13
