### ISSUE TITLE
Unexpected character * (Origin: bugzilla #594592)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3511]
status RESOLVED severity *normal* in component *general* for *---*
Reported in version *1.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-09-09 06:23:56 +0000, Johnny Willemsen wrote:

> After upgrade to 1.6.1 we get this new warning:
> [Details] Generating /web/www/Doxygen/staging_area/Current/ACE_wrappers/ace/ARGV.h:84: Error: Unexpected character `"'
> 
> The documentation in the header is below, see that we have a "
> 
> /**
>  * @class ACE_ARGV_T
>  *
>  * @brief Builds a counted argument vector (ala argc/argv) from either
>  * a string or a set of separate tokens. This class preserves whitespace
>  * within tokens only if the whitespace-containing token is enclosed in
>  * either single (') or double (") quotes. This is consistent with the
>  * expected behavior if an argument vector obtained using this class is
>  * passed to, for example, ACE_Get_Opt.
>  *
>  * This class can substitute environment variable values for tokens that
>  * are environment variable references (e.g., @c $VAR). This only works
>  * if the token is an environment variable reference and nothing else; it
>  * doesn't substitute environment variable references within a token.
>  * For example, @c $HOME/file will not substitute the value of the HOME
>  * environment variable.
>  */

On 2009-09-24 13:29:24 +0000, Tom Fredrik Klaussen wrote:

> Just adding a me too on this one, we have the same issue when building the Coin library. I've checked, and this works fine with Doxygen 1.5.9, but breaks with 1.6.1.
> 
> See http://www.coin3d.org/lib/coin for several examples of Doxygen breaking.

On 2009-10-10 14:56:14 +0000, Dimitri van Heesch wrote:

> Confirmed. Should be fixed in the next subversion update.

On 2009-12-30 13:38:40 +0000, Dimitri van Heesch wrote:

> This bug was previously marked ASSIGNED, which means it should be fixed in
> doxygen version 1.6.2. Please verify if this is indeed the case and reopen the
> bug if you think it is not fixed (include any additional information that you
> think can be relevant).

On 2010-01-12 17:48:16 +0000, Tom Fredrik Klaussen wrote:

> Verified working in doxygen 1.6.2
> 
> Thanks a lot :-)
