### ISSUE TITLE
Doxygen fails to build with --with-clang-static on MacOSX 10.10.3 (Origin: bugzilla #751522)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5815]
status RESOLVED severity *blocker* in component *build* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-06-25 23:10:22 +0000, adam.getchell@gmail.com wrote:

> It works if the --with-libclang option is not used.
> 
> ââ[adam][Hapkido][~]
> âââª brew install doxygen --with-doxywizard --with-graphviz
> ==> Downloading http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.9.1.src.tar.gz
> Already downloaded: /Library/Caches/Homebrew/doxygen-1.8.9.1.tar.gz
> ==> Patching
> patching file addon/doxywizard/Makefile.in
> Hunk # 1 succeeded at 31 (offset 1 line).
> patching file configure
> Hunk # 1 succeeded at 583 (offset 5 lines).
> ==> ./configure --prefix /usr/local/Cellar/doxygen/1.8.9.1 --with-doxywizard
> ==> make
> ==> make MAN1DIR=share/man/man1 install
> 

On 2015-06-26 18:29:02 +0000, Dimitri van Heesch wrote:

> So where does it fail? and what is being patched? and do you have libclang installed?

On 2015-06-26 18:59:41 +0000, adam.getchell@gmail.com wrote:

> Yes, I have libclang installed. Also, the previous version of Doxygen worked.
> 
> ââ[adam][hapkido][Â±][master â][~/Presentations]
> âââª locate libclang
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/darwin/libclang_rt.10.4.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/darwin/libclang_rt.cc_kext.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/darwin/libclang_rt.cc_kext_ios5.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/darwin/libclang_rt.eprintf.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/darwin/libclang_rt.ios.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/darwin/libclang_rt.osx.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/darwin/libclang_rt.profile_ios.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/darwin/libclang_rt.profile_osx.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/macho_embedded/libclang_rt.hard_pic.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/macho_embedded/libclang_rt.hard_static.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/macho_embedded/libclang_rt.soft_pic.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.1.0/lib/macho_embedded/libclang_rt.soft_static.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
> /usr/local/Cellar/llvm/3.6.1/lib/libclang.3.6.dylib
> /usr/local/Cellar/llvm/3.6.1/lib/libclang.dylib
> /usr/local/Cellar/llvm/3.6.1/lib/libclangARCMigrate.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangAST.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangASTMatchers.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangAnalysis.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangApplyReplacements.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangBasic.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangCodeGen.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangDriver.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangDynamicASTMatchers.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangEdit.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangFormat.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangFrontend.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangFrontendTool.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangIndex.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangLex.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangParse.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangQuery.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangRename.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangRewrite.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangRewriteFrontend.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangSema.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangSerialization.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangStaticAnalyzerCheckers.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangStaticAnalyzerCore.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangStaticAnalyzerFrontend.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangTidy.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangTidyGoogleModule.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangTidyLLVMModule.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangTidyMiscModule.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangTidyReadabilityModule.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangTidyUtils.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangTooling.a
> /usr/local/Cellar/llvm/3.6.1/lib/libclangToolingCore.a
> 
> Here's the error building with homebrew:
> 
> ââ[adam][hapkido][Â±][master â][~/Presentations]
> âââª brew install doxygen --with-doxywizard --with-graphviz --with-libclang
> ==> Downloading http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.9.1.src.tar.gz
> ######################################################################## 100.0%
> ==> Patching
> patching file addon/doxywizard/Makefile.in
> Hunk # 1 succeeded at 31 (offset 1 line).
> patching file configure
> Hunk # 1 succeeded at 583 (offset 5 lines).
> ==> ./configure --prefix /usr/local/Cellar/doxygen/1.8.9.1 --with-doxywizard --w
> ==> make
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [../bin/doxygen] Error 1
> make[1]: *** [all] Error 2
> make: *** [all] Error 2
> 
> READ THIS: https://git.io/brew-troubleshooting
> 
> These open issues may also help:
> Doxygen failed to build on 10.10.3 (https://github.com/Homebrew/homebrew/issues/39642)

On 2015-06-26 19:20:25 +0000, Dimitri van Heesch wrote:

> The error is still not very useful and it is still not clear to me what the patching of Makefile.in does (it is a homebrew patch apparently). 
> Also 'ld' doesn't even say which symbols is cannot find...
> 
> Maybe good to know, that I've replaced the build system with one based on cmake in the meantime, so maybe good to check if the latest version from GitHub works (it does for me).

On 2015-06-29 03:40:51 +0000, Kevin McBride wrote:

> I ran a test build using "-Duse_libclang=ON" and the CMake build system worked.  I am setting this bug to ASSIGNED so that Dimitri can decide on the disposition of this bug.

On 2015-06-29 18:15:28 +0000, Dimitri van Heesch wrote:

> Hi Kevin, please don't set bugs to ASSIGNED. I use this state to mark a bug as "fixed but not in the official release".
