### ISSUE TITLE
master does not compile on Mac 12.2.1

### ISSUE THREAD

**Issue by couet** [doxygen/doxygen#9136]
I get this:

```
[ 93%] Building CXX object src/CMakeFiles/doxymain.dir/template.cpp.o
/Users/couet/git/doxygen/src/template.cpp:349:17: error: 'get<bool, std::monostate, bool, int, QCString, std::shared_ptr<TemplateStructIntf>, std::shared_ptr<TemplateListIntf>, std::function<TemplateVariant (const std::vector<TemplateVariant> &)>, std::weak_ptr<TemplateStructIntf>>' is unavailable: introduced in macOS 10.13
    return std::get<bool>(m_variant) == std::get<bool>(other.m_variant);
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/variant:1500:22: note: 'get<bool, std::monostate, bool, int, QCString, std::shared_ptr<TemplateStructIntf>, std::shared_ptr<TemplateListIntf>, std::function<TemplateVariant (const std::vector<TemplateVariant> &)>, std::weak_ptr<TemplateStructIntf>>' has been explicitly marked unavailable here
constexpr const _Tp& get(const variant<_Types...>& __v) {
                     ^
/Users/couet/git/doxygen/src/template.cpp:349:46: error: 'get<bool, std::monostate, bool, int, QCString, std::shared_ptr<TemplateStructIntf>, std::shared_ptr<TemplateListIntf>, std::function<TemplateVariant (const std::vector<TemplateVariant> &)>, std::weak_ptr<TemplateStructIntf>>' is unavailable: introduced in macOS 10.13
    return std::get<bool>(m_variant) == std::get<bool>(other.m_variant);
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/c++/v1/variant:1483:16: note: 'get<bool, std::monostate, bool, int, QCString, std::shared_ptr<TemplateStructIntf>, std::shared_ptr<TemplateListIntf>, std::function<TemplateVariant (const std::vector<TemplateVariant> &)>, std::weak_ptr<TemplateStructIntf>>' has been explicitly marked unavailable here
constexpr _Tp& get(variant<_Types...>& __v) {
               ^
/Users/couet/git/doxygen/src/template.cpp:353:17: error: 'get<int, std::monostate, bool, int, QCString, std::shared_ptr<TemplateStructIntf>, std::shared_ptr<TemplateListIntf>, std::function<TemplateVariant (const std::vector<TemplateVariant> &)>, std::weak_ptr<TemplateStructIntf>>' is unavailable: introduced in macOS 10.13
    return std::get<int>(m_variant) == std::get<int>(other.m_variant);
                ^
 ....
```

**Comment by couet** [comment]
for info (in case you need it):
```
build % cmake ../
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found BISON: /usr/local/bin/bison (found version "3.4") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Success
-- Found Iconv: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/lib/libiconv.tbd  
-- One (and only one) of the ICONV_ACCEPTS_... tests must pass
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Success
-- Performing Test ICONV_ACCEPTS_CONST_INPUT
-- Performing Test ICONV_ACCEPTS_CONST_INPUT - Failed
-- The javacc executable not found, using existing files
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/couet/git/doxygen/build

```

**Comment by ferdymercury** [comment]
Maybe related: https://stackoverflow.com/questions/52521388/stdvariantget-does-not-compile-with-apple-llvm-10-0

**Comment by doxygen** [comment]
@couet strange, you seem to be using a newer compiler than me. What do

```
xcodebuild -version
clang --version
sw_vers
```
report?

**Comment by doxygen** [comment]
@couet Nevermind, I think I found the issue. The deployment target was option dependent. In my case, I had options enabled such that it was high enough (>=10.14). Anything lower gives the error you reported. Please check if the commit  fixes the problem.

**Comment by couet** [comment]
I got the new commit. It compiles fine on Mac now. Thanks !
